[tox]
envlist = copying,{py310,py313,py314}-{lint,tests,color,cli}
skip_missing_interpreters = True

[testenv]
allowlist_externals =
    /bin/bash
    /usr/bin/bash
deps =
    iotlabcli
    -rtests_utils/test-requirements.txt
commands =
    tests:  {[testenv:tests]commands}
    lint:   {[testenv:lint]commands}
    cli:    {[testenv:cli]commands}
    color:  {[testenv:color]commands}

[testenv:tests]
commands =
    pytest

[testenv:color]
commands =
    pip install .[color_serial]

[testenv:lint]
commands =
    ruff format --check iotlabaggregator
    ruff check iotlabaggregator
    isort --check-only iotlabaggregator

[testenv:copying]
allowlist_externals =
    /bin/bash
    /usr/bin/bash
commands =
    bash tests_utils/check_license.sh

[testenv:cli]
allowlist_externals =
    /bin/bash
    /usr/bin/bash
commands =
    bash -exc "for i in *_aggregator; do $i --help >/dev/null; done"
